name: freecol # you probably want to 'snapcraft register <name>'
base: core20
compression: lzo
version: '0.12'
summary: Colonization Strategy Game
description: 'FreeCol is a turn-based strategy game based on the old game
  Colonization, and similar to Civilization. The objective of the game is
  to create an independent nation.
  
  You start with only a few colonists defying the stormy seas in their search
  for new land. Will you guide them on the Colonization of a New World?'


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


parts:
  freecol:
    plugin: dump
    source: http://prdownloads.sourceforge.net/freecol/freecol-0.12.0.zip?download
    source-type: zip
    stage-packages: [openjdk-11-jre]
    override-stage: |
      snapcraftctl stage
      chmod +x freecol/freecol
    prime:
      - -freecol/freecol.cmd
      - -freecol/developer.pdf


apps:
  freecol:
    extensions: [gnome-3-38]
    command: freecol/freecol
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
